import { createSlice } from '@reduxjs/toolkit'
//This imports the createSlice function from Redux Toolkit.createSlice is a utility that simplifies creating Redux slices of state along with reducers and actions in one place.

const initialState = {
    user: null,
}

export const userSlice = createSlice({

    //You're creating a new slice called userSlice using createSlice. The createSlice function takes an object with the following properties

    name: 'counter',

    //The name of the slice is 'counter', which helps identify this slice of state in the Redux store.It’s also used for naming the generated action types like counter/ setUserDetails.

    initialState,

    // This is the initial state for this slice.As defined earlier, it’s { user: null }

    reducers: {

        //This is an object that contains functions(reducers) that modify the state based on actions.In this case, there’s one reducer:

        setUserDetails: (state, action) => {

            //This reducer updates the user in the state.The action parameter contains the dispatched action, and the payload is the data passed when the action is dispatched.So, when setUserDetails is called, it will set state.user to whatever is passed in the action.payload.

            state.user = action.payload

            //This line updates the user property of the state with the data from the action.payload

            // console.log("userDetails", action.payload);

        }
    },
})

// Action creators are generated for each case reducer function
export const { setUserDetails } = userSlice.actions

//userSlice.actions: This line extracts and exports the setUserDetails action creator from the userSlice object.The userSlice.actions object contains all the action creators(functions) automatically generated by Redux Toolkit based on the reducers defined in the slice.You export setUserDetails so that you can dispatch it elsewhere in your app.

export default userSlice.reducer

//This exports the reducer function (the one that was created automatically by createSlice) as the default export from this file.This reducer will handle updates to the state for this slice(i.e., the user state).